### ISSUE TITLE
TOC 功能无效

### ISSUE THREAD

**Issue by simowce** [erlzhang/jekyll-theme-persephone#11]
Hi, 我创建了一个博客，已经按照您的设置在 Gemfile 加上了：
```
gem "jekyll-theme-persephone"
gem "jekyll-toc"
```
也在 `_config.yml` 里面把主题设置为了 theme: jekyll-theme-persephone，以及加上了：

```
plugins:
  - jekyll-feed
  - jekyll-toc
```

但是在有目录的文章依旧没有侧边 TOC 出现，不知道是什么原因呢？

**Comment by erlzhang** [comment]
可以参考一下jekyll-toc插件的官方说明，TOC是需要在每一篇文章中的头部设置 `toc: true` 以手动开启的，如下：

```yaml
title: xxxxx
toc: true
```

如果需要每一篇文章都开启，可以在 `_config.yml` 中设一个默认配置：

```yaml
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true
```
